export const Questions2 = [
    {
      prompt: "How Are YOu?",
      optionA: "4",
      optionB: "0",
      optionC: "1",
      optionD: "3",
      asnwer: "optionB",
    },
      {
        prompt: "I am fine?",
        optionA: "4",
        optionB: "0",
        optionC: "1",
        optionD: "3",
        asnwer: "optionA",
      },
      {
        prompt: "Sum 2-2?",
        optionA: "60",
        optionB: "02",
        optionC: "1",
        optionD: "3",
        asnwer: "optionA",
      },
      {
        prompt: "Sum 2+2?",
        optionA: "4",
        optionB: "0",
        optionC: "1",
        optionD: "3",
        asnwer: "optionA",
      },
      {
        prompt: " 1=='1'?",
        optionA: "4",
        optionB: "True",
        optionC: "False",
        optionD: "3",
        asnwer: "optionB",
      },
      {
        prompt: " 1==='1'?",
        optionA: "4",
        optionB: "False",
        optionC: "True",
        optionD: "3",
        asnwer: "optionB",
      },
    ];